#!/bin/bash

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

if [ -f "~/.nvm/nvm.sh" ];then
  echo '✔ nvm is already installed'
else
  echo "==> nvm isn't installed, installing it..."
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
  source ~/.nvm/nvm.sh
fi

echo 'Cheking for node version...'
if [ -f ".node-version" ] && [ "$(nvm version 2>/dev/null)" != "$(cat .node-version)" ]; then
  echo "==> Node $(cat .node-version) isn't installed, installing it..."
  nvm install $(cat .node-version)
  which bundle >/dev/null 2>&1
else
  echo '✔ Node is already installed'
fi

if [ -f "package.json" ]; then
  echo "==> Installing dependencies…"
  npm install
fi
